export const icon = {
  //BottomTab navigation icon
  home: require('../assets/home.png'),
  homeUn: require('../assets/homeUn.png'),
  HeartUn: require('../assets/HeartUn.png'),
  SearchSel: require('../assets/SearchSel.png'),
  SearchUn: require('../assets/SearchUn.png'),
  ProfileSel: require('../assets/ProfileSel.png'),
  ProfileUn: require('../assets/ProfileUn.png'),
  leftArrow: require('../assets/leftArrow.png'),
  Schoudle: require('../assets/Schoudle.png'),
  Copoun: require('../assets/CouponLogo.png'),
  Copoun1: require('../assets/CouponLogo1.png'),
  Copoun2: require('../assets/CouponLogo2.png'),
  Copoun3: require('../assets/CouponLogo3.png'),
  closewhite: require('../assets/closewhite.png'),
  copy: require('../assets/copy.png'),
  info: require('../assets/info.png'),
  Cart: require('../assets/Cart.png'),

  Help: require('../assets/Help.png'),
  Notifications: require('../assets/Notification.png'),
  refer: require('../assets/refer.png'),
  Connect: require('../assets/Connectwithus.png'),
  Myorders: require('../assets/Myorders.png'),
  SearchClose: require('../assets/close-circle.png'),
  sortDown: require('../assets/Back.png'),
  Heart: require('../assets/Heart.png'),
  // FillHeart: require('../assets/FillHeart.png'),

  Coupon: require('../assets/Coupon.png'),
  Plus: require('../assets/Plus.png'),
  Search: require('../assets/Search.png'),
  BackBotton: require('../assets/BackBotton.png'),
  Addition: require('../assets/Addition.png'),
  Minus: require('../assets/Minus.png'),
  instant: require('../assets/instant.png'),
  DownloadIcon: require('../assets/DownloadIcon.png'),
  Share: require('../assets/Share.png'),
  InProgress: require('../assets/InProgress.png'),
  Success: require('../assets/Success.png'),
  PaymentSucess: require('../assets/PaymentSucess.png'),

  AppliedCoupon: require('../assets/AppliedCoupon.png'),
  close: require('../assets/close.png'),
  DeliveryNow: require('../assets/DeliveryNow.png'),
  scheduledelivery: require('../assets/scheduledelivery.png'),
  Edit: require('../assets/Edit.png'),
  SelectedDelivery: require('../assets/SelectedDelivery.png'),
  UnSelectedDelivery: require('../assets/UnSelectedDelivery.png'),
  HomeAddress: require('../assets/HomeAddress.png'),
  OfficeAddress: require('../assets/OfficeAddress.png'),
  HDFCIcon: require('../assets/HDFCIcon.png'),
  SelectedButton: require('../assets/SelectedButton.png'),
  UnSelectedButton: require('../assets/UnSelectedButton.png'),
  UPIicon: require('../assets/UPIicon.png'),
  GPayIcon: require('../assets/GPayIcon.png'),
  PaypalIcon: require('../assets/PaypalIcon.png'),
  CashOnIcon: require('../assets/CashOnIcon.png'),
  Icicicon: require('../assets/Icicicon.png'),
  Indianflaf: require('../assets/Indianflaf.png'),
  HomeSCreenCoupon: require('../assets/HomeSCreenCoupon.png'),
  Ellipsewithplus: require('../assets/Ellipsewithplus.png'),

  Filtercoffee: require('../assets/Filtercoffee.png'),
  cappuccino: require('../assets/2.png'),
  Malli: require('../assets/SukkuMalliCoffee.png'),
  Espresso: require('../assets/Espresso.png'),

  donut: require('../assets/donut.png'),
  frenchfries: require('../assets/french-fries.png'),
  macaroons: require('../assets/macaroons.png'),
  Heartcokkies: require('../assets/Heartcokkies.png'),
  BCokkies: require('../assets/BCokkies.png'),
  BCokkies1: require('../assets/Bcokkies1.png'),
  Oatmealraisin: require('../assets/Oatmealraisin.png'),

  bloodymary: require('../assets/bloodymary.png'),
  cocktail: require('../assets/cocktail.png'),
  cosmopolitan: require('../assets/cosmopolitan.png'),
  mojito: require('../assets/mojito.png'),
  pinacolada: require('../assets/pinacolada.png'),
  daiquiri: require('../assets/daiquiri.png'),

  Home1: require('../assets/1.png'),
  Home2: require('../assets/slider2.png'),

  CartOrderSlider: require('../assets/CartOrderSlider.png'),
  AddressOrderSlider: require('../assets/AddressOrderSlider.png'),
  PaymentOrderSlider: require('../assets/PaymentOrderSlider.png'),
  includeImage: require('../assets/includeImage.png'),

  CafeSeed: require('../assets/CafeSeed.png'),
  coffeeback: require('../assets/coffeeback.png'),
  Messanger: require('../assets/Messanger.png'),
  WhatsApp: require('../assets/WhatsApp.png'),
  Gmail: require('../assets/Gmail.png'),
  Skype: require('../assets/Skype.png'),
  invitefriends: require('../assets/invitefriends.png'),
  Businessesinvite: require('../assets/Businessesinvite.png'),
  instagram: require('../assets/instagram.png'),
  telegram: require('../assets/telegram.png'),

  LoginBackground: require('../assets/LoginBackground.png'),
};

export default {icon};
